name: Build
on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checks-Out Repository
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Setup Node.js Environment
              uses: actions/setup-node@v4.2.0
              with:
                  node-version: 20
            - name: Setup pnpm
              run: |
                  npm install --global pnpm
            - name: Fetching Node Modules
              run: |
                  pnpm install
            - name: Build Distributable
              run: |
                  pnpm lint
                  pnpm build
